name: Lambda & EventBridge 배포

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest # Ubuntu 환경에서 실행

    steps:
      # 1. 코드 체크아웃
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      # 2. AWS CLI 설정
      - name: AWS CLI 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. env 설정
      - name: env 설정
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env

      # 4. npm 다운로드
      - name: npm 다운로드
        run: npm i

      # 5. Lambda 함수 코드 압축
      - name: Lambda 함수 코드 압축
        run: |
          zip -r function.zip .  # 현재 디렉터리 내의 모든 파일을 압축합니다.

      # 6. Lambda 함수 코드 업데이트
      - name: Lambda 함수 코드 업데이트
        run: |
          aws lambda update-function-code --function-name ghost-commit-lambda --zip-file fileb://function.zip

      # 7. EventBridge 규칙(rule) 설정
      - name: Set up EventBridge Rule
        run: |
          aws events put-rule --schedule-expression "rate(1 minute)" --name "daily-ghost-commit" --state ENABLED

      # 8. EventBridge 규칙에 Lambda 함수를 실행 타겟으로 추가
      - name: EventBridge 규칙에 Lambda 함수를 실행 타겟으로 추가
        run: |
          aws events put-targets --rule "daily-ghost-commit" --targets "Id"="1","Arn"="arn:aws:lambda:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:function:ghost-commit-lambda"
